### ISSUE TITLE
Implement OpenJourneyPlanner query and serialisation format

### ISSUE THREAD

**Issue by skinkie** [rutebanken/OpenTripPlanner#39]
## Expected behavior
Able to interface with OpenJourneyPlanner clients.

## Observed behavior
OpenTripPlanner implements it only REST API.

## Version of OTP used (exact commit hash or JAR name)
master branch

**Comment by t2gran** [comment]
Moved to OTP master project: https://github.com/opentripplanner/OpenTripPlanner/issues/2753
