### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by piotrek-toolla** [rutebanken/OpenTripPlanner#74]
## Expected behavior
I'd like to know what is the difference between this fork and the one from Helsinki or the original one (https://github.com/opentripplanner/OpenTripPlanner).
I'd like to know how to successfully build and start the application (the original build command doesn't work)

## Observed behavior
I see the original docs and not of this fork.

## Version of OTP used (exact commit hash or JAR name)
origin/rutebanken_develop

## Data sets in use (links to GTFS and OSM PBF files)
n/a

## Command line used to start OTP
unknown command line to start OTP

## Router config and graph build config JSON
n/a

## Steps to reproduce the problem
n/a

**Comment by t2gran** [comment]
This is [Entur](entur.org) fork, witch we at the Entur do our development. Many of the branches here is based on the main project (opentripplanner) and we are a major contributor to the next  version of OTP - OTP2. 

We do not provide any support on this fork. But, if you explain why you want to run any of our branches, we might help you, or point you to the right place.

**Comment by piotrek-toolla** [comment]
@t2gran OpenTripPlanner is being implemented by TOOLLA (a technical partner of InnoBaltica) as a part of an international project co-financed from the Interreg South Baltic Program.

The beneficiary of the implementation is the 100% public in-house company: InnoBaltica which is a regional ticketing integrator in public transport. The implementation is carried out as a pilot investment of two partners in Interconnect project: Region Blekinge (southern Sweden) and InnoBaltica (Pomeranian Region in northern Poland). As part of the pilot project, it is planned to create an integrated transport database, a passenger information portal with a travel planner, and as a result - a joint international ticket. In the implementation, InnoBaltica uses leading and modern solutions. InnoBaltica has already implemented Chouette data base for PT static information.

The above explanation gives you a background for why the solution is modelled on the leading European implementation of ENTUR, but also on the experiences of project partners in building solutions for cross-border connections (German - Danish and Estonian - Finnish).

The project has numerous participants from the South Baltic Region. Please visit the project website: http://interconnect.one/partners-and-contact

The project became the flagship project of the EU Strategy for SBR, what we are very proud of.

We will be very happy to use your experience in implementing OTP, which will be highlighted in further project reporting.

**Comment by piotrek-toolla** [comment]
@t2gran Is there anything else I can do to explain why I need your support?

**Comment by t2gran** [comment]
Thank you for the introduction to yourself, the company and the project. 

So, there are 4 different versions of OTP that might intrest you: 
 - [Entur OTP1](https://github.com/entur/OpenTripPlanner/tree/rutebanken_develop) - make sure you use the `rutebanken_develop` branch
 - HSL OTP1
 - Main OTP1 (dev-1.x) or release 1.4
 - [Main OTP2 ](https://github.com/opentripplanner/OpenTripPlanner/tree/dev-2.x). Make sure you look at the dev-2.x brach. 

Entur will use the Main OPT2 in production before it is released. When it is close to feature compliant with OTP1 we plan to make a Beta/RC. We also want to develop a new GraphQL API based on/merge of the HSL GraphQL API (GTFS) and Entur GraphQL API (Transmodel). But we wan´t rush this, and also this allow us to have a period for bugfixing and so on - before the final 2.0 release.  

Changes to the HSL is here: https://groups.google.com/forum/#!searchin/opentripplanner-dev/HSL%7Csort:date/opentripplanner-dev/Ui00F2m1mfg/s3htuihWBQAJ

Unfortunately I do not have a list of bugfixes/features for Entur and the best I have is to look at the commits. But the big thing is support for Netex and Siri in addition to GTFS.

## What to use?
I would go for OTP with a GraphQL API. The Main OTP1 GraphQL API is not maintained. The supported API for OTP1 is the REST API.  Entur OTP1 Transmodel API have the riches feature set and HSL GraphQL very similar, just using GTFS terminology. OTP2 is not ready for production, but you can try it out and see if it meets your needs - you should plan for migrating to OTP2 in the long run.

**Comment by t2gran** [comment]
You should be able to use the `--help` on how to run OTP - regardless of version. Here is my setup for Entur OTP1 (from Intellij) :
```
--build /.../otp/graphs/ruter-gtfs-prod                      --build the graph
--server --basePath /.../otp --router ruter-gtfs-prod        -- run OTP
```
 Make sure you have enough memory, setting the Java VM switch `-Xmx8g`.

**Comment by t2gran** [comment]
The last post here https://github.com/opentripplanner/OpenTripPlanner/issues/2904 show the flow and parameters for OTP2. In OTP2 the last argument is the path to the directory where all config and datafiles must be. All parameters are flags (no arguments). OTP2 datasources can be configured in the build config.
